version: "3"

services:
  postgres_forecast:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TESTING: 1
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_forecast:5432/postgres
      - GIT_PYTHON_REFRESH=quiet
      - LOG_LEVEL=DEBUG
    command: >
      bash -c "sleep 10
      && pytest --cov=./pvnet_app
      && coverage report -m
      && coverage xml
      && cp .coverage ./tests/
      && cp coverage.xml ./tests/"
    depends_on:
      - postgres_forecast
    volumes:
      - ./tests/:/app/tests
      - ./pvnet_app/:/app/pvnet_app
