name: Conda pytest
on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  push_to_registry:
    name: Build docker file for testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults
          auto-update-conda: true
          auto-activate-base: true

      - name: Install the conda
        shell: bash -l {0}
        run: |
          conda install -c conda-forge xesmf esmpy -y

      - name: Install the repo
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: run pytest
        shell: bash -l {0}
        run: |
          python -m pytest
